"""Pull every note and comment the owner left on the review deck.

The deck's speaker notes were generated by slides_deck_v8.py, so anything the
owner typed is whatever is NOT that generated text. This diffs each slide's
notes against the generated version and prints only the additions, plus every
Drive comment and reply.
"""
import json
import pickle
import re
from pathlib import Path

from google.auth.transport.requests import Request
from googleapiclient.discovery import build

ROOT = Path(__file__).resolve().parents[1]
TOK = Path(r"C:\Users\avina\OneDrive\Desktop\Claude Projects\XL Eagle"
           r"\Tools and Dashboards\Pickle creation\tokens"
           r"\token_slides_info_xleagle_com.pickle")
PRES = "19WBr6buuAkN-8SpspUz68KZgdxjeYMGuZrBJWMeF-O0"
SHOTS = ROOT / "manifest/picture_v8_shots.json"
OUT = ROOT / "manifest/deck_feedback.json"


def creds():
    c = pickle.load(open(TOK, "rb"))
    if not c.valid and c.expired and c.refresh_token:
        c.refresh(Request())
        pickle.dump(c, open(TOK, "wb"))
    return c


def notes_text(slide) -> str:
    np = slide.get("slideProperties", {}).get("notesPage", {})
    out = []
    for e in np.get("pageElements", []):
        tx = e.get("shape", {}).get("text", {})
        for te in tx.get("textElements", []):
            if "textRun" in te:
                out.append(te["textRun"].get("content", ""))
    return "".join(out).strip()


def generated_note(s: dict) -> str:
    return (f"shot {s['name']}  |  EDL segment {s['span']}  |  "
            f"kind {s['kind']}\n"
            f"asset: {s.get('asset') or '(rendered graphic)'}\n"
            f"spec: {s['spec']}\n\n"
            f"why this picture: {s.get('why', '')}")


def norm(t: str) -> str:
    return re.sub(r"\s+", " ", t or "").strip()


def main() -> int:
    c = creds()
    slides_api = build("slides", "v1", credentials=c, cache_discovery=False)
    drive = build("drive", "v3", credentials=c, cache_discovery=False)

    d = slides_api.presentations().get(presentationId=PRES).execute()
    sl = d["slides"]
    shots = json.loads(SHOTS.read_text(encoding="utf-8"))
    print(f"{len(sl)} slides, {len(shots)} shots in manifest\n")

    found = []
    for i, s in enumerate(sl):
        actual = notes_text(s)
        gen = generated_note(shots[i]) if i < len(shots) else ""
        a, g = norm(actual), norm(gen)
        if not a or a == g:
            continue
        extra = a
        # strip the generated portion wherever it sits
        for chunk in (g, norm(gen.split("why this picture:")[0])):
            if chunk and chunk in extra:
                extra = extra.replace(chunk, " ").strip()
        why = norm(shots[i].get("why", "")) if i < len(shots) else ""
        if why and why in extra:
            extra = extra.replace(why, " ").strip()
        extra = re.sub(r"\s+", " ", extra).strip(" |")
        if len(extra) < 3:
            continue
        found.append({"slide": i + 1,
                      "shot": shots[i]["name"] if i < len(shots) else "",
                      "prog_start": shots[i]["prog_start"] if i < len(shots) else None,
                      "added_note": extra})
        print(f"===== SLIDE {i+1} "
              f"({shots[i]['prog_start']:.2f}s)" if i < len(shots)
              else f"===== SLIDE {i+1}")
        print(extra)
        print()

    print(f"\n{len(found)} slides carry added notes\n")

    print("===== DRIVE COMMENTS =====")
    comments = []
    tok = None
    while True:
        r = drive.comments().list(
            fileId=PRES, pageSize=100, pageToken=tok,
            fields=("nextPageToken,comments(id,author/displayName,content,"
                    "quotedFileContent/value,anchor,resolved,createdTime,"
                    "replies(author/displayName,content,createdTime))")
        ).execute()
        comments += r.get("comments", [])
        tok = r.get("nextPageToken")
        if not tok:
            break
    if not comments:
        print("(none)")
    for cm in comments:
        print(f"- [{cm.get('createdTime','')[:19]}] "
              f"{cm.get('author',{}).get('displayName','?')}"
              f"{' (resolved)' if cm.get('resolved') else ''}")
        if cm.get("quotedFileContent"):
            print(f"    on: {cm['quotedFileContent'].get('value','')[:90]}")
        print(f"    {cm.get('content','')}")
        for rp in cm.get("replies", []):
            print(f"      reply {rp.get('author',{}).get('displayName','?')}: "
                  f"{rp.get('content','')}")
    OUT.write_text(json.dumps(
        {"notes": found, "comments": comments}, indent=2), encoding="utf-8")
    print(f"\n[OK] {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
